export const PAYMENT_STRATEGIES = 'PAYMENT_STRATEGIES';
export const WEBHOOK_EVENT_HANDLERS = 'WEBHOOK_EVENT_HANDLERS';
export const CHECKOUT_SESSION_COMPLETED = 'checkout.session.completed';
export const INVOICE_PAYMENT_SUCCEEDED = 'invoice.payment_succeeded';
export const CHECKOUT_ORDER_APPROVED = 'CHECKOUT.ORDER.APPROVED';
export const BILLING_SUBSCRIPTION_ACTIVATED = 'BILLING.SUBSCRIPTION.ACTIVATED';
