name: Deploy
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger hook
        env:
          RENDER_REDEPLOY_URL: ${{ secrets.RENDER_DEPLOY_URL }}
        run: |
          curl -X GET $RENDER_REDEPLOY_URL
